### ISSUE TITLE
Incomplete domain check - wildcard cookies

### ISSUE THREAD

**Issue by wainglaister** [haifengkao/YWebView#1]
This check on wether to allow cookies is incomplete because it doesn't allow partial domain matches:

```
    // Is the cookie for current domain?
    if (![cookie.domain hasSuffix:validDomain]) {
```

instead it should be:

```
    if (![validDomain hasSuffix:cookie.domain] && ![cookie.domain hasSuffix:validDomain]) {
```

**Comment by wainglaister** [comment]
Hmmm, it seems that if the URL doesn't have a scheme it can't work out the host so we may want a more comprehensive change...

**Comment by haifengkao** [comment]
"URL doesn't have a scheme" -> NSURL always has a scheme.

**Comment by haifengkao** [comment]
You are right about partial domain matches. I have merged it.
