### ISSUE TITLE
YWebView doesn't store cookie between sessions

### ISSUE THREAD

**Issue by neooleg** [haifengkao/YWebView#10]
## STR

1. Start app which persists cookie, e.g. on login
1. Login and make sure that cookie was set
1. Swipe and start app again

## AR
There is no stored cookie, so Web app *is not logged in*

## ER
Cookie should be stored after app restart

**Comment by haifengkao** [comment]
It's possible that the cookie doesn't have the `expires` property.
https://stackoverflow.com/questions/11570737/shared-instance-of-nshttpcookiestorage-does-not-persist-cookies

**Comment by neooleg** [comment]
Agree, let's close it then.

BTW, there is behavior in browser to store cookie event typed `session`.
