### ISSUE TITLE
Javascript syntax error

### ISSUE THREAD

**Issue by wainglaister** [haifengkao/YWebView#3]
This line has an extra [ that shouldn't be there (in the javascript):

```
[script appendFormat:@"if ([cookieNames.indexOf('%@') == -1) { document.cookie='%@'; };\n", cookie.name, [self javascriptStringWithCookie:cookie]];
```

**Comment by haifengkao** [comment]
Fixed.
But this code won't be executed anyway unless there is a way to inject cookies properly
