### ISSUE TITLE
Private category, App approval?

### ISSUE THREAD

**Issue by SentoCrespo** [haifengkao/YWebView#6]
Hello there!

I checked the SO answer and the OP wrote there that he was using a private category, is this applying to your wrapper?
http://stackoverflow.com/questions/26573137/can-i-set-the-cookies-to-be-used-by-a-wkwebview

Have you uploaded any app to the store using your YWebView?

Thanks a lot!

**Comment by haifengkao** [comment]
LOL. You can upload it without any problems. He didn't publish the category in the beginning, so he calls it "private category". It's not the same as the private category which is forbidden by Apple.
